//Auth 
export const SET_USER = 'SET_USER';
export const UNSET_USER = 'UNSET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

//Chatroom
export const CREATE_NEW_CHATROOM = 'CREATE_NEW_CHATROOM';
export const CREATE_NEW_CHATROOM_ERROR = 'CREATE_NEW_CHATROOM_ERROR';
export const GET_CHATROOMS = 'GET_CHATROOMS';
export const GET_CHATROOMS_ERROR = 'GET_CHATROOMS_ERROR';
export const GET_CHATROOM = 'GET_CHATROOM';
export const GET_CHATROOM_ERROR = 'GET_CHATROOM_ERROR';

//Channel
export const CREATE_NEW_CATEGORY = 'CREATE_NEW_CATEGORY';
export const CREATE_NEW_CATEGORY_ERROR = 'CREATE_NEW_CATEGORY_ERROR';
export const CREATE_NEW_CHANNEL = 'CREATE_NEW_CHANNEL';
export const CREATE_NEW_CHANNEL_ERROR = 'CREATE_NEW_CHANNEL_ERROR';
export const GET_CHANNELS = 'GET_CHANNELS';
export const GET_CHANNELS_ERROR = 'GET_CHANNELS_ERROR';
export const GET_CHANNEL = 'GET_CHANNEL';
// export const GET_CHANNEL_ERROR = 'GET_CHANNEL_ERROR';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

//Channel Comments
export const GET_CHANNEL_COMMENTS = 'GET_CHANNEL_COMMENTS';
export const GET_CHANNEL_COMMENTS_ERROR = 'GET_CHANNEL_COMMENTS_ERROR';
